# Generated by Django 5.0.1 on 2024-02-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaces',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
