# Generated by Django 5.0.1 on 2024-02-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_workspaces_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemembers',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
