# Generated by Django 5.0.1 on 2024-02-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_workspacemembers_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemembers',
            name='about_me',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workspacemembers',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
