# Generated by Django 5.0.1 on 2024-02-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_alter_workspacemembers_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaces',
            name='workspace_name',
            field=models.CharField(max_length=50),
        ),
    ]
