# Generated by Django 5.0.1 on 2024-03-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_invitationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaces',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
