# Generated by Django 5.0.1 on 2024-03-18 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0006_invitationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=178)),
                ('topic', models.CharField(max_length=178)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspaces.workspacemembers')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspaces')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_chats.workspacegroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspacemembers')),
            ],
        ),
    ]
