# Generated by Django 5.0.1 on 2024-03-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacegroup',
            name='is_private',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
