# Generated by Django 5.0.1 on 2024-04-02 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chats', '0002_workspacegroup_is_private'),
        ('workspaces', '0007_workspaces_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.CharField(max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('is_send', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_send_messages', to='workspaces.workspacemembers')),
            ],
        ),
    ]
