# Generated by Django 5.0.1 on 2024-04-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chats', '0003_groupchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmessage',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
