# Generated by Django 5.0.1 on 2024-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chats', '0005_remove_groupchatmessage_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchatmessage',
            name='type',
            field=models.CharField(default='text_message'),
        ),
    ]
