# Generated by Django 5.0.1 on 2024-04-19 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chats', '0006_groupchatmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatmessage',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
