# Generated by Django 5.0.1 on 2024-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
