# Generated by Django 5.0.1 on 2024-03-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='group_id',
            field=models.CharField(max_length=100),
        ),
    ]
