# Generated by Django 5.0.1 on 2024-04-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_chats', '0003_rename_group_id_chatmessage_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_name',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
