# Generated by Django 5.0.1 on 2024-04-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_chats', '0004_remove_chatmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(default='text_message'),
        ),
    ]
