# Generated by Django 5.0.1 on 2024-04-19 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_chats', '0005_chatmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
